kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: backend-url
  namespace: blu-live-clinic
spec:
  # Host removed to bypass permission errors; OCP will auto-generate it
  to:
    kind: Service
    name: backend
    weight: 100
  port:
    targetPort: 5000
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None